<h1>Transformaciones </h1>

In [37]:
import numpy as np
import pandas as pd

In [38]:
df_asma_data_2021 = pd.read_csv('./datos/Datos_proyecto_II_BI_2021.csv', sep=',', encoding = 'latin-1')
df_asma_data_2017 = pd.read_csv('./datos/Datos_proyecto_II_BI_2017.csv', sep=',', encoding = 'latin-1')

C:\Users\El supremo\AppData\Local\Temp\ipykernel_12756\4267242611.py:1: DtypeWarning: Columns (334,410,412,540,541,543,545,549,552,553,554,555,556,557) have mixed types. Specify dtype option on import or set low_memory=False.
  df_asma_data_2021 = pd.read_csv('./datos/Datos_proyecto_II_BI_2021.csv', sep=',', encoding = 'latin-1')
C:\Users\El supremo\AppData\Local\Temp\ipykernel_12756\4267242611.py:2: DtypeWarning: Columns (145,295,297,380,381,383,469,495,496,499,500,501,508,509,510,511) have mixed types. Specify dtype option on import or set low_memory=False.
  df_asma_data_2017 = pd.read_csv('./datos/Datos_proyecto_II_BI_2017.csv', sep=',', encoding = 'latin-1')

In [39]:
def transform_data2021(df):
    columnas_de_interes_2021 = [
    "NPCEP5",
    "NOMBRE_LOCALIDAD",
    "NPCEP4",
    "MPIO",
    "NPCHP18AA",
    "NPCHP18AB",
    "NPCHP18AC",
    "NPCHP18AD",
    "NPCHP18AE",
    "NPCHP18AF",
    "NPCHP18AG",
    "NPCHP18AH",
    "NPCHP18AI",
    "NPCHP18AI1",
    "NPCHP18AJ",
    "NPCHP18AK",
    "NPCHP18AL",
    "NPCHP18AM",
    "NPCHP18AN",
    "NPCHP18AO"]
    df_asma_asma_2021 = df[columnas_de_interes_2021]
    df_asma_bogota_2021=df_asma_asma_2021[df_asma_asma_2021["MPIO"]==11001]
    df_asma_bogota_2021['ANIO']=2021

    df_asma_bogota_2021.rename(columns = {
        "NPCEP5":"sexo",
    "NOMBRE_LOCALIDAD":"localidad",
    "NPCEP4":"edad",
    "MPIO":"municipio",
    'NPCHP18AA':'Transmilenio', 
    'NPCHP18AB':'SITP',
    'NPCHP18AC':'buseta_o_colectivo', 
    "NPCHP18AD": "automovil_particular",
    "NPCHP18AE": "Taxi",
    "NPCHP18AF": "Motocicleta",
    "NPCHP18AG": "Bicicleta",
    "NPCHP18AH": "Ruta_escolar",
    "NPCHP18AI": "A_pie",
    "NPCHP18AI1": "Bus_intermunicipal",
    "NPCHP18AJ": "bicitaxi_o_mototaxi",
    "NPCHP18AK": "particulares_plataformas_o_aplicaciones",
    "NPCHP18AL": "vehículo_patineta_moto_electicos",
    "NPCHP18AM": "caballo",
    "NPCHP18AN": "otros",
    "NPCHP18AO": "no_se_desplaza",
                    }, inplace = True)
    return df_asma_bogota_2021

In [40]:
df_2021_transform = transform_data2021(df_asma_data_2021)
df_2021_transform

C:\Users\El supremo\AppData\Local\Temp\ipykernel_12756\1083904316.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_asma_bogota_2021['ANIO']=2021
C:\Users\El supremo\AppData\Local\Temp\ipykernel_12756\1083904316.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_asma_bogota_2021.rename(columns = {

,sexo,localidad,edad,municipio,Transmilenio,SITP,buseta_o_colectivo,automovil_particular,Taxi,Motocicleta,...,Ruta_escolar,A_pie,Bus_intermunicipal,bicitaxi_o_mototaxi,particulares_plataformas_o_aplicaciones,vehículo_patineta_moto_electicos,caballo,otros,no_se_desplaza,ANIO
0,2,Bosa,70,11001,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
1,2,Bosa,60,11001,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
2,1,Usme,13,11001,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2021
3,1,Fontibon,38,11001,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
4,2,Fontibon,56,11001,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8625,2,Bosa,35,11001,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
8626,1,Bosa,9,11001,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2021
8627,1,Bosa,0,11001,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
8628,1,Bosa,37,11001,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
8629,2,Bosa,10,11001,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2021

In [43]:
def transform_data2017(df):
    columnas_de_interes_2017 = ["LOCALIDAD_TEX","NPCEP5", 
                                "NPCEP4", "DPTOMPIO", "NPCFP14B", 
                                "NPCHP18A", 
                                "NPCHP18B", "NPCHP18C", "NPCHP18D", 
                                "NPCHP18E", "NPCHP18F", "NPCHP18G", 
                                "NPCHP18H", "NPCHP18I", "NPCHP18J", 
                                "NPCHP18K", "NPCHP18L", "NPCHP18M"]
    df_asma_asma_2017 = df[columnas_de_interes_2017]
    df_asma_bogota_2017=df_asma_asma_2017[df_asma_asma_2017["DPTOMPIO"]==11001]
    df_asma_bogota_2017['ANIO']=2017
    df_asma_bogota_2017["no_se_desplaza"]= 1
    df_asma_bogota_2017["vehículo_patineta_moto_electicos"]= 1
    df_asma_bogota_2017["particulares_plataformas_o_aplicaciones"]= 1


    df_asma_bogota_2017.rename(columns = {
        "NPCEP5":"sexo",
    "LOCALIDAD_TEX":"localidad",
    "NPCEP4":"edad",
    "DPTOMPIO":"municipio",
    'NPCHP18A':'Transmilenio', 
    'NPCHP18B':'SITP',
    'NPCHP18C':'buseta_o_colectivo', 
    "NPCHP18D": "automovil_particular",
    "NPCHP18E": "Taxi",
    "NPCHP18F": "Motocicleta",
    "NPCHP18G": "Bicicleta",
    "NPCHP18H": "Ruta_escolar",
    "NPCHP18I": "A_pie",
    "NPCHP18AJ": "Bus_intermunicipal",
    "NPCHP18K": "bicitaxi_o_mototaxi",
    "NPCHP18L": "caballo",
    "NPCHP18M": "otros",
   
                    }, inplace = True)
    return df_asma_bogota_2017

In [44]:
df_2017_transform = transform_data2017(df_asma_data_2017)
df_2017_transform

C:\Users\El supremo\AppData\Local\Temp\ipykernel_12756\866660176.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_asma_bogota_2017['ANIO']=2017
C:\Users\El supremo\AppData\Local\Temp\ipykernel_12756\866660176.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_asma_bogota_2017["no_se_desplaza"]= 1
C:\Users\El supremo\AppData\Local\Temp\ipykernel_12756\866660176.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_asma_bogota_2017["vehículo_patineta_moto_electicos"]= 1
C:\Users\El supremo\AppData\Local\Temp\ipykernel_12756\866660176.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_asma_bogota_2017["particulares_plataformas_o_aplicaciones"]= 1
C:\Users\El supremo\AppData\Local\Temp\ipykernel_12756\866660176.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_asma_bogota_2017.rename(columns = {

,localidad,sexo,edad,municipio,NPCFP14B,Transmilenio,SITP,buseta_o_colectivo,automovil_particular,Taxi,...,Ruta_escolar,A_pie,NPCHP18J,bicitaxi_o_mototaxi,caballo,otros,ANIO,no_se_desplaza,vehículo_patineta_moto_electicos,particulares_plataformas_o_aplicaciones
0,SUBA,1,39,11001,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2017,1,1,1
1,USAQUEN,2,22,11001,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2017,1,1,1
2,USAQUEN,2,29,11001,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2017,1,1,1
3,USAQUEN,1,11,11001,1,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,NaN,2017,1,1,1
4,SUBA,2,37,11001,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2017,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4722,SUBA,2,34,11001,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2017,1,1,1
4723,USME,2,28,11001,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2017,1,1,1
4724,USME,2,8,11001,2,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,2017,1,1,1
4725,USME,1,7,11001,2,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,2017,1,1,1
4726,USME,2,3,11001,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2017,1,1,1

In [45]:
def join_df (df_2017,df_2021):
    frames = [df_2017,df_2021]

    return pd.concat(frames)

In [46]:
join_data=join_df(df_2017_transform,df_2021_transform)
join_data

,localidad,sexo,edad,municipio,NPCFP14B,Transmilenio,SITP,buseta_o_colectivo,automovil_particular,Taxi,...,A_pie,NPCHP18J,bicitaxi_o_mototaxi,caballo,otros,ANIO,no_se_desplaza,vehículo_patineta_moto_electicos,particulares_plataformas_o_aplicaciones,Bus_intermunicipal
0,SUBA,1,39,11001,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2017,1.0,1.0,1.0,NaN
1,USAQUEN,2,22,11001,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2017,1.0,1.0,1.0,NaN
2,USAQUEN,2,29,11001,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2017,1.0,1.0,1.0,NaN
3,USAQUEN,1,11,11001,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2017,1.0,1.0,1.0,NaN
4,SUBA,2,37,11001,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2017,1.0,1.0,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8625,Bosa,2,35,11001,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,NaN
8626,Bosa,1,9,11001,NaN,2.0,2.0,2.0,2.0,2.0,...,2.0,NaN,2.0,NaN,2.0,2021,2.0,2.0,2.0,2.0
8627,Bosa,1,0,11001,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,NaN
8628,Bosa,1,37,11001,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2021,NaN,NaN,NaN,NaN
8629,Bosa,2,10,11001,NaN,2.0,2.0,2.0,2.0,2.0,...,1.0,NaN,2.0,NaN,2.0,2021,2.0,2.0,2.0,2.0